CREATE TABLE usuarios (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(50) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    role ENUM('USER', 'ADMIN') NOT NULL,
    ativo TINYINT NOT NULL DEFAULT 1
);